### ISSUE TITLE
Add new plugins for anti spam

### ISSUE THREAD

**Issue by Muttahir786** [uniborg/uniborg#17]
Add some plugins to use antispam/antiflood like !ban or mute etc

**Comment by Streetwalrus** [comment]
This isn't really within scope for stdplugins. These are meant mostly for the following purposes:
1. extending Telegram functionality by providing features the official clients do not
1. bringing some bot features that are nice to have in one on one chats
What you're asking for is something more akin to a group administration bot (which is imo pretty pointless unless it can actually operate autonomously), so it'd be better as a separate project. uniborg itself can be used as a library for bot development, and the workflow would be the same as in stdborg since the plugin system is baked in.

**Comment by Lonami** [comment]
No reason to keep this open due to the mentioned points.
